# Generated by Django 4.0.4 on 2022-05-16 14:08

from django.db import migrations, models
import myapi.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CriminalImgDetect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('query_image_url', models.ImageField(blank=True, null=True, upload_to=myapi.models.upload_to_detected)),
                ('image_url', models.ImageField(blank=True, null=True, upload_to='')),
                ('crimes', models.CharField(blank=True, max_length=100, null=True)),
                ('encoding', models.CharField(blank=True, max_length=5000, null=True)),
                ('current_status', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Criminals',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('image_url', models.ImageField(blank=True, null=True, upload_to=myapi.models.upload_to)),
                ('crimes', models.CharField(blank=True, max_length=100, null=True)),
                ('encoding', models.CharField(blank=True, max_length=5000, null=True)),
                ('current_status', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CriminalVideoDetect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_video_url', models.FileField(blank=True, null=True, upload_to=myapi.models.upload_video_to_detected)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
