# Generated by Django 4.0.4 on 2022-05-16 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='criminals',
            old_name='uuid',
            new_name='id',
        ),
    ]
