# Generated by Django 4.0.4 on 2022-05-18 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_appusers'),
    ]

    operations = [
        migrations.AddField(
            model_name='appusers',
            name='last_image_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='appusers',
            name='last_video_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
