# Generated by Django 4.0.4 on 2022-05-19 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapi', '0004_appusers_last_image_url_appusers_last_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appusers',
            name='email',
        ),
        migrations.AlterField(
            model_name='appusers',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
