# Generated by Django 4.0.4 on 2022-05-26 11:55

from django.db import migrations, models
import myapi.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0005_remove_appusers_email_alter_appusers_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appusers',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to=myapi.models.upload_users_to),
        ),
    ]
